[package]
name = "discord-bot-v2"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv_codegen = "0.15.0"
poise = "0.6.1"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
